export const SERVICIO_PERSONAJES = "characters?"
export const CANTIDAD_REGISTROS = "limit=10&"
export const PAGINA_SOLICITADA = "offset="
export const API_KEY = "apikey="
export const LISTA_FAVORITOS = "comicsFavoritos"